export const SCHEMA_STATEMENTS = [
    `CREATE TABLE IF NOT EXISTS subscriptions (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    name        TEXT    NOT NULL DEFAULT '',
    url         TEXT    NOT NULL,
    type        TEXT    NOT NULL CHECK(type IN ('source', 'rule', 'txtTocRule', 'dictRule')),
    enabled     INTEGER NOT NULL DEFAULT 1,
    last_synced TEXT    DEFAULT NULL,
    item_count  INTEGER DEFAULT 0,
    created_at  TEXT    NOT NULL DEFAULT (datetime('now'))
  )`,
    `ALTER TABLE subscriptions DROP CONSTRAINT IF EXISTS subscriptions_type_check`,
    `ALTER TABLE subscriptions ADD CONSTRAINT subscriptions_type_check CHECK(type IN ('source', 'rule', 'txtTocRule', 'dictRule'))`,
    `CREATE TABLE IF NOT EXISTS sources (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    subscription_id INTEGER NOT NULL REFERENCES subscriptions(id) ON DELETE CASCADE,
    book_source_url TEXT    NOT NULL,
    name            TEXT    NOT NULL DEFAULT '',
    group_name      TEXT    DEFAULT '',
    enabled         INTEGER NOT NULL DEFAULT 1,
    raw_json        TEXT    NOT NULL,
    test_url        TEXT    DEFAULT NULL,
    updated_at      TEXT    NOT NULL DEFAULT (datetime('now')),
    is_available    INTEGER NOT NULL DEFAULT 1,
    last_checked    TEXT    DEFAULT NULL,
    url_hash        TEXT    NOT NULL DEFAULT ''
  )`,
    `ALTER TABLE sources DROP CONSTRAINT IF EXISTS sources_subscription_id_book_source_url_key`,
    `CREATE TABLE IF NOT EXISTS rules (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    subscription_id INTEGER NOT NULL REFERENCES subscriptions(id) ON DELETE CASCADE,
    name            TEXT    NOT NULL DEFAULT '',
    pattern         TEXT    NOT NULL DEFAULT '',
    replacement     TEXT    NOT NULL DEFAULT '',
    enabled         INTEGER NOT NULL DEFAULT 1,
    raw_json        TEXT    NOT NULL,
    updated_at      TEXT    NOT NULL DEFAULT (datetime('now')),
    pattern_hash    TEXT    NOT NULL DEFAULT ''
  )`,
    `ALTER TABLE rules DROP CONSTRAINT IF EXISTS rules_subscription_id_name_pattern_key`,
    `CREATE TABLE IF NOT EXISTS txt_toc_rules (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    subscription_id INTEGER NOT NULL REFERENCES subscriptions(id) ON DELETE CASCADE,
    name            TEXT    NOT NULL DEFAULT '',
    rule            TEXT    NOT NULL DEFAULT '',
    example         TEXT    DEFAULT NULL,
    serial_number   INTEGER NOT NULL DEFAULT -1,
    enabled         INTEGER NOT NULL DEFAULT 1,
    raw_json        TEXT    NOT NULL,
    updated_at      TEXT    NOT NULL DEFAULT (datetime('now')),
    rule_hash       TEXT    NOT NULL DEFAULT ''
  )`,
    `ALTER TABLE txt_toc_rules DROP CONSTRAINT IF EXISTS txt_toc_rules_subscription_id_name_rule_hash_key`,
    `CREATE TABLE IF NOT EXISTS dict_rules (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    subscription_id INTEGER NOT NULL REFERENCES subscriptions(id) ON DELETE CASCADE,
    name            TEXT    NOT NULL DEFAULT '',
    url_rule        TEXT    NOT NULL DEFAULT '',
    show_rule       TEXT    NOT NULL DEFAULT '',
    enabled         INTEGER NOT NULL DEFAULT 1,
    sort_number     INTEGER NOT NULL DEFAULT 0,
    raw_json        TEXT    NOT NULL,
    updated_at      TEXT    NOT NULL DEFAULT (datetime('now'))
  )`,
    `ALTER TABLE dict_rules DROP CONSTRAINT IF EXISTS dict_rules_subscription_id_name_key`,
    `CREATE INDEX IF NOT EXISTS idx_subscriptions_type    ON subscriptions(type)`,
    `CREATE INDEX IF NOT EXISTS idx_sources_subscription  ON sources(subscription_id)`,
    `CREATE INDEX IF NOT EXISTS idx_sources_enabled       ON sources(enabled)`,
    `CREATE INDEX IF NOT EXISTS idx_rules_subscription    ON rules(subscription_id)`,
    `CREATE INDEX IF NOT EXISTS idx_rules_enabled         ON rules(enabled)`,
    `CREATE INDEX IF NOT EXISTS idx_sources_available       ON sources(is_available)`,
    `DROP INDEX IF EXISTS idx_sources_unique`,
    `CREATE UNIQUE INDEX IF NOT EXISTS idx_sources_unique ON sources(subscription_id, url_hash)`,
    `DROP INDEX IF EXISTS idx_rules_unique`,
    `CREATE UNIQUE INDEX IF NOT EXISTS idx_rules_unique   ON rules(subscription_id, name, pattern_hash)`,
    `CREATE INDEX IF NOT EXISTS idx_txt_toc_rules_subscription ON txt_toc_rules(subscription_id)`,
    `CREATE INDEX IF NOT EXISTS idx_txt_toc_rules_enabled      ON txt_toc_rules(enabled)`,
    `DROP INDEX IF EXISTS idx_txt_toc_rules_unique`,
    `CREATE UNIQUE INDEX IF NOT EXISTS idx_txt_toc_rules_unique ON txt_toc_rules(subscription_id, name, rule_hash)`,
    `CREATE INDEX IF NOT EXISTS idx_dict_rules_subscription    ON dict_rules(subscription_id)`,
    `CREATE INDEX IF NOT EXISTS idx_dict_rules_enabled         ON dict_rules(enabled)`,
    `DROP INDEX IF EXISTS idx_dict_rules_unique`,
    `CREATE UNIQUE INDEX IF NOT EXISTS idx_dict_rules_unique   ON dict_rules(subscription_id, name)`,
    `CREATE TABLE IF NOT EXISTS passkeys (
    id          TEXT PRIMARY KEY,
    public_key  TEXT NOT NULL,
    counter     INTEGER NOT NULL DEFAULT 0,
    transports  TEXT,
    name        TEXT NOT NULL,
    created_at  TEXT NOT NULL DEFAULT (datetime('now'))
  )`,
    `CREATE TABLE IF NOT EXISTS custom_themes (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    name        TEXT    NOT NULL,
    config      TEXT    NOT NULL,
    preview_url TEXT,
    created_at  TEXT    NOT NULL DEFAULT (datetime('now'))
  )`,
    `CREATE TABLE IF NOT EXISTS system_config (
    key   TEXT PRIMARY KEY,
    value TEXT
  )`,
    `CREATE TABLE IF NOT EXISTS parse_history (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    url         TEXT    UNIQUE NOT NULL,
    updated_at  TEXT    NOT NULL DEFAULT (datetime('now'))
  )`,
    `DROP INDEX IF EXISTS idx_parse_history_url_unique`,
    `CREATE UNIQUE INDEX IF NOT EXISTS idx_parse_history_url_unique ON parse_history(url)`,
    `CREATE INDEX IF NOT EXISTS idx_parse_history_updated_at ON parse_history(updated_at)`,
    // ─── 段评 ────────────────────────────────────────────────────
    // book_key/chapter_key 由书名作者与章节标题散列而来，换书源后批注依然命中
    `CREATE TABLE IF NOT EXISTS review_chapters (
    id            INTEGER PRIMARY KEY AUTOINCREMENT,
    book_key      TEXT    NOT NULL,
    chapter_key   TEXT    NOT NULL,
    book_name     TEXT    NOT NULL DEFAULT '',
    author        TEXT    NOT NULL DEFAULT '',
    chapter_title TEXT    NOT NULL DEFAULT '',
    para_count    INTEGER NOT NULL DEFAULT 0,
    status        TEXT    NOT NULL DEFAULT 'pending',
    error         TEXT    DEFAULT NULL,
    generated_at  TEXT    DEFAULT NULL,
    created_at    TEXT    NOT NULL DEFAULT (datetime('now'))
  )`,
    `DROP INDEX IF EXISTS idx_review_chapters_unique`,
    `CREATE UNIQUE INDEX IF NOT EXISTS idx_review_chapters_unique ON review_chapters(book_key, chapter_key)`,
    `CREATE INDEX IF NOT EXISTS idx_review_chapters_status ON review_chapters(status)`,
    // 记下 App 请求时带来的定位信息，诊断和补生成就不必再手工输入
    `ALTER TABLE review_chapters ADD COLUMN book_url TEXT DEFAULT NULL`,
    `ALTER TABLE review_chapters ADD COLUMN origin_url TEXT DEFAULT NULL`,
    // para_index 为 -1 时表示章节标题；para_hash 用于校验段落是否被净化规则改动
    `CREATE TABLE IF NOT EXISTS reviews (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    book_key    TEXT    NOT NULL,
    chapter_key TEXT    NOT NULL,
    para_index  INTEGER NOT NULL DEFAULT 1,
    para_hash   TEXT    NOT NULL DEFAULT '',
    author      TEXT    NOT NULL DEFAULT '',
    avatar      TEXT    DEFAULT NULL,
    badge       TEXT    DEFAULT NULL,
    content     TEXT    NOT NULL,
    reply_to    INTEGER DEFAULT NULL,
    origin      TEXT    NOT NULL DEFAULT 'ai',
    like_count  INTEGER NOT NULL DEFAULT 0,
    created_at  TEXT    NOT NULL DEFAULT (datetime('now'))
  )`,
    `CREATE INDEX IF NOT EXISTS idx_reviews_locate ON reviews(book_key, chapter_key, para_index)`,
    `CREATE INDEX IF NOT EXISTS idx_reviews_reply_to ON reviews(reply_to)`,
    `CREATE INDEX IF NOT EXISTS idx_reviews_origin ON reviews(origin)`
];
